apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-server
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        component: "{{ .Chart.Name }}-server"
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.parseServer.image }}"
        imagePullPolicy: {{ default "" .Values.parseServer.imagePullPolicy | quote }}
        env:
        - name: PARSE_SERVER_HOST
          value: "0.0.0.0"
        - name: PARSE_SERVER_PORT
          value: {{ .Values.parseServer.port | quote }}
        - name: PARSE_SERVER_MOUNT_PATH
          value: {{ .Values.parseServer.mountPath | quote }}
        - name: PARSE_SERVER_APP_ID
          value: {{ .Values.parseServer.appId | quote }}
        - name: PARSE_SERVER_MASTER_KEY
          value: {{ .Values.parseServer.masterKey | quote }}
        - name: MONGODB_HOST
          value: {{ template "mongodb.fullname" . }}
        - name: MONGODB_PORT
          value: "27017"
        ports:
        - name: server-http
          containerPort: 1337
        # livenessProbe:
          # httpGet:
            # path: /
            # port: http
          # initialDelaySeconds: 120
          # timeoutSeconds: 5
        # readinessProbe:
          # exec:
            # command:
            # - sh
            # - -c
            # - nami status ghost | grep "ghost is running"
          # initialDelaySeconds: 5
          # timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: parse-data
          mountPath: /bitnami/parse
      volumes:
      - name: parse-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
